apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: "0.14.1"
      helm:
        releaseName: arc-runners
        values: |
          githubConfigUrl: https://github.com/blaisethompson/homelab-gitops
          githubConfigSecret: arc-github-secret
          controllerServiceAccountNamespace: arc-systems
          controllerServiceAccountName: arc-controller-gha-rs-controller
          runnerScaleSetName: arc-runners
          minRunners: 0
          maxRunners: 5
    - repoURL: https://github.com/blaisethompson/homelab-arc
      targetRevision: main
      path: runners
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
