---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arc-github-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgBwSn5psDcfrfAMJm1ZzjQhRn11uzVJ/+xuZmTEhwK3zUi6G14FEBKb86GkYGGUL12bPqxGH1pv8hTBlGqqpT6JJDX3FtfeaOTYUhp/6Pv5fGmKuCCZwcxJnQiEICyk4fsdskOJNBwSF81/YPD9Het+HZfoxBN+aftT51xuWQt99XfL8VBnZzowFS8YdOwYWUXHH/kRRi8FC6vOjXG2QGYYdCDoeDKDDPP/zCe0Fuu+jsxqQ7gWdFr1od1HJHz8xoO00IKrlr7xoOtZ9EW2pnOqCElZfyPGDerz8c+RLFBt1wuFZQOOYPRnenMBTeagMDiGGJQfglqZv7a4nM7d/2Y80ugCWXPUjuN3my/s8+RrAAE2ME3yyubqOUWnLcWOckWhrmfr+77mdAhUCVsrP1tTin5RFs3PmD7Rf/GCOSa3qyNGkJ0bF3FBLfxHyf35zHsIy3em1BNPRsoxTltQZFXg2KnefBQnLxrVTSNDTBZE+znbeH/+BjIg4YnZfIN89cbmCF3PiykXqdYVwvh81mdDKxuOqP6dYdtHcmaASLFa20TtNKQUchTUBIM2ZrZ0qlZ9t5MJ+iN8PSpyENpNhd+JgrRoaZGL2O6VYNYQoIvBRw4TXrzfc7pDYevZDMjhqHm4HK4j1KHz9Lw5IxBpcclRyl6ovN6jrzNp8sn/877tjnNR00RLsB2rRetzV7jeU9EqzOslALvYlD638h2FjVEzUwRycKlheuB1VanTxpI2bIvA5K4uCMXt
  template:
    metadata:
      name: arc-github-secret
      namespace: arc-runners
    type: Opaque
