apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: arc-runners
  namespace: arc-runners
  labels:
    actions.github.com/scale-set-name: arc-runners
    actions.github.com/scale-set-version: "0.14.1"
spec:
  githubConfigUrl: https://github.com/blaisethompson/homelab-gitops
  githubConfigSecret: arc-github-secret
  runnerScaleSetName: arc-runners
  runnerScaleSetLabels:
    - homelab
  minRunners: 0
  maxRunners: 5
  runnerGroup: Default
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: [ "/home/runner/run.sh" ]
